version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    networks:
      - server
      - client
    environment:
      - "JDBC_URL=jdbc:postgresql://db:5432/app"
      - "JDBC_DRIVER=org.postgresql.Driver"
      - "JDBC_USERNAME=postgres"
      - "JDBC_PASSWORD=tour"
      - "JDBC_MAX_POOL=10"
    ports:
      - "8080:80"
      - "5006:5006"
    volumes:
      - "./build/libs:/app"
    depends_on:
      - db
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - "./postgres-data:/var/lib"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tour
      POSTGRES_DB: app
    restart: always
    networks:
      - server
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    ports:
      - '80:80'
    volumes:
      - ./client/build:/usr/local/apache2/htdocs
networks:
  server:
  client:
