FROM openjdk:17-alpine

EXPOSE 8080 8081 5006

RUN apk add --no-cache fontconfig ttf-dejavu

VOLUME /app

WORKDIR /app

ENTRYPOINT java -jar -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006 shadow.jar